apiVersion: v1
description: Brigade provides event-driven scripting of Kubernetes pipelines.
name: brigade
version: 0.3.1
# Note that we use appVersion to get images, so make sure this is correct.
appVersion: v0.3.0
