[[constraint]]
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/gosuri/uitable"

[[constraint]]
  name = "github.com/oklog/ulid"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/gin-gonic/gin.v1"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/api"

[[constraint]]
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"
