[[constraint]]
  name = "github.com/bacongobbler/browser"
  version = "v1.0.1"

[[constraint]]
  name = "github.com/google/go-github"

[[constraint]]
  name = "github.com/gosuri/uitable"

[[constraint]]
  name = "github.com/oklog/ulid"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "gopkg.in/gin-gonic/gin.v1"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-7.0"

[[constraint]]
  branch = "master"
  name = "github.com/Masterminds/kitt"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.6.1"

[[constraint]]
  name = "github.com/emicklei/go-restful-openapi"
  version = "0.9.1"
