[[constraint]]
  name = "github.com/bacongobbler/browser"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "^21.0.0"

[[constraint]]
  name = "github.com/gosuri/uitable"
  branch = "master"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "^1.3.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.3"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "gopkg.in/gin-gonic/gin.v1"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "^2.2.2"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-7.0"

[[constraint]]
  name = "github.com/Masterminds/kitt"
  branch = "master"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.7.1"

[[constraint]]
  name = "github.com/emicklei/go-restful-openapi"
  version = "^1.0.0"

[[constraint]]
  name = "gopkg.in/AlecAivazis/survey.v1"
  version = "1.6.1"

[[constraint]]
  name = "github.com/cloudevents/sdk-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/slok/brigadeterm"
  version = "v0.11.1"

[[constraint]]
  name = "github.com/mattn/go-runewidth"
  version = "v0.0.2"

[[constraint]]
  name = "github.com/rivo/tview"
  revision = "6614b16d9037759065eac63d8fb3d8408e63e222"
