{{ if .Values.api.enabled }}
{{ $fname := include "brigade.api.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
{{ if .Values.rbac.enabled }}
---
kind: Role
apiVersion: {{ template "brigade.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "secrets", "pods/log"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: {{ template "brigade.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ $fname }}
roleRef:
  kind: Role
  name: {{ $fname }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
{{ end }}
