{{ if .Values.controller.enabled }}{{ $fullname := include "brigade.ctrl.fullname" . }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ $fullname }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    role: controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $fullname }}
        role: controller
    spec:
      serviceAccountName: {{ $fullname }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.controller.registry }}/{{ .Values.controller.name }}:{{ default .Chart.AppVersion .Values.controller.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.controller.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        command:
        - /usr/bin/brigade-controller
        {{ if .Values.controller.workerResources }}
        args:
        {{ if .Values.controller.workerResources.requests }}
        - -worker-requests-cpu={{ default "" .Values.controller.workerResources.requests.cpu }}
        - -worker-requests-memory={{ default "" .Values.controller.workerResources.requests.memory }}
        {{- end }}
        {{ if .Values.controller.workerResources.limits }}
        - -worker-limits-cpu={{ default "" .Values.controller.workerResources.limits.cpu }}
        - -worker-limits-memory={{ default "" .Values.controller.workerResources.limits.memory }}
        {{- end }}
        {{- end }}
        env:
          - name: BRIGADE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: BRIGADE_WORKER_IMAGE
            value: "{{ .Values.worker.registry }}/{{ .Values.worker.name }}:{{ default .Chart.AppVersion .Values.worker.tag }}"
          - name: BRIGADE_WORKER_PULL_POLICY
            value: {{ default "IfNotPresent" .Values.worker.pullPolicy }}
          - name: BRIGADE_WORKER_SERVICE_ACCOUNT
            value: {{ default "brigade-worker" .Values.worker.serviceAccount.name }}
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}
{{ end }}