{{ if .Values.controller.enabled }}
{{ $fname := include "brigade.ctrl.fullname" . }}
{{ $serviceAccount := default $fname .Values.controller.serviceAccount.name }}
{{ if .Values.controller.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
{{ end }}
{{ if .Values.rbac.enabled }}
---
kind: Role
apiVersion: {{ template "brigade.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["pods", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: {{ template "brigade.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccount }}
roleRef:
  kind: Role
  name: {{ $fname }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
{{ end }}{{/* end if controller enabled */}}
