{{ if .Values.cr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "brigade.cr.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: gateway
    type: dockerhub
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.cr.service.externalPort }}
    targetPort: {{ .Values.cr.service.internalPort }}
    protocol: TCP
    name: {{ .Values.cr.service.name }}
  selector:
    app: {{ template "brigade.fullname" . }}
    role: gateway
    type: dockerhub
{{ end }}
