{{ if .Values.cr.enabled }}
{{ $fullname := include "brigade.cr.fullname" . }}
{{ $serviceAccount := default $fullname .Values.cr.serviceAccount.name }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    role: gateway
    type: dockerhub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "brigade.fullname" . }}
        role: gateway
        type: dockerhub
    spec:
      serviceAccountName: {{ $serviceAccount }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.cr.registry }}/{{ .Values.cr.name }}:{{ default .Chart.AppVersion .Values.cr.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.cr.pullPolicy }}
        ports:
        - containerPort: {{ .Values.cr.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.cr.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.cr.service.internalPort }}
        env:
          - name: BRIGADE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}
{{ end }}
