{{ if .Values.vacuum.enabled }}
{{ $fname := include "brigade.vacuum.fullname" . }}
{{ $serviceAccount := default "brigade-vacuum" .Values.vacuum.serviceAccount.name }}
{{ if .Values.vacuum.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ if .Values.rbac.enabled }}
---
kind: Role
apiVersion: {{ template "brigade.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: {{ template "brigade.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app.kubernetes.io/name: {{ template "brigade.fullname" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccount }}
roleRef:
  kind: Role
  name: {{ $fname }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}{{/* end if rbac enabled */}}
{{ end }}{{/* end if create service account */}}
{{ end }}{{/* end if vacuum enabled */}}
