{{ $fname := include "acid.gw.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fname }}
  labels:
    app: {{ template "acid.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ if .Values.rbac.enabled }}
---
kind: Role
apiVersion: {{ template "acid.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app: {{ template "acid.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: {{ template "acid.rbac.version" }}
metadata:
  name: {{ $fname }}
  labels:
    app: {{ template "acid.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ $fname }}
roleRef:
  kind: Role
  name: {{ $fname }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
