# Name of the project, in the form "user/project"
project: "deis/empty-testbed"

# Domain/Org/Project
repository: "github.com/deis/empty-testbed"

# The definitive clone URL. This can be any Git-supported URL format.
cloneURL: "https://github.com/deis/empty-testbed.git"

# Used by GitHub and other services to compute hook HMACs.
sharedSecret: "IBrakeForSeaBeasts"

# OPTIONAL: Use this to have Acid update your project about the build.
# You probably want this if you want pull requests or commits to show
# the build status.
github: {}
#   token: "github oauth token"

# OPTIONAL: Use this for private repositories
# This is the PRIVATE key that Acid will use to clone a private repo.
# You should generate a special key for this. Don't reuse another one.
# sshKey: |-
#  -----BEGIN RSA PRIVATE KEY-----
#  IIEpAIBAAKCAg1wyZD164xNLrANjRrcsbieLwHJ6fKD3LC19E...
#  ...
#  ...
#  -----END RSA PRIVATE KEY-----

# OPTIONAL: Items in the 'secrets' array can be mounted as environment variables by
# the acid.js
#
# Example:
#
# In JS, do this:
#
#   events.push = function(e) {
#     j = new Job("example")
#     j.env= {"MY_ENV_VAR", e.secrets.myVar}
#   }
#
# And here, add this:
#
#   secrets:
#     myVar: "super awesome"
#
# Inside of the job's pod, $MY_ENV_VAR = "super awesome"
secrets: {}

# OPTIONAL: Namespace into which builds will be deployed.
# Using this has implications for what you can access, so don't set this unless
# you know what you are doing.
# namespace: "default"

# OPTIONAL: vcsSidecar is the image that fetches a repo from a VCS
# The default version can do a wide variety of VCS systems, but is focused on
# supporting Git.
# vcsSidecar: "acidic.azurecr.io/vcs-sidecar:latest"

