baseURL = "https://docs.brigade.sh/"
title = "Brigade"
theme = "techdoc-brigade"
canonifyURLs = "true"
relativeURLs = "true"

[params]
  title = "Brigade"
  description = "Brigade - Event-driven scripting for Kubernetes."

# main docs 'index' menu on left
[[menu.index]]
    name = "Home"
    url = "https://brigade.sh"
    weight = 10
[[menu.index]]
    name = "Getting Started"
    url = "/intro/"
    weight = 20
    identifier = "intro"
    [[menu.index]]
    name = "Overview"
    url = "/intro/overview/"
    weight = 21
    parent = "intro"
    [[menu.index]]
    name = "Quickstart"
    url = "/intro/quickstart/"
    weight = 22
    parent = "intro"
    [[menu.index]]
    name = "Installing Brigade"
    url = "/intro/install/"
    weight = 23
    parent = "intro"
    [[menu.index]]
    name = "Tutorial 1: Writing a CI pipeline"
    url = "/intro/tutorial01/"
    weight = 24
    parent = "intro"
    [[menu.index]]
    name = "Tutorial 2: Setup GitHub"
    url = "/intro/tutorial02/"
    weight = 25
    parent = "intro"
    [[menu.index]]
    name = "Tutorial 3: Projects & Events"
    url = "/intro/tutorial03/"
    weight = 26
    parent = "intro"
    [[menu.index]]
    name = "Tutorial 4: Writing a Test"
    url = "/intro/tutorial04/"
    weight = 27
    parent = "intro"
    [[menu.index]]
    name = "Tutorial 5: Writing Efficient Pipelines"
    url = "/intro/writing-efficient-pipelines/"
    weight = 28
    parent = "intro"
    [[menu.index]]
    name = "What to Read Next"
    url = "/intro/readnext/"
    weight = 29
    parent = "intro"
[[menu.index]]
    name = "Topic Guides"
    url = "/topics/"
    weight = 40
    identifier = "topics"
    [[menu.index]]
    name = "Design"
    url = "/topics/design/"
    weight = 41
    parent = "topics"
    [[menu.index]]
    name = "Scripting Guide"
    url = "/topics/scripting/"
    weight = 42
    parent = "topics"
    [[menu.index]]
    name = "The Brigade.js API"
    url = "/topics/javascript/"
    weight = 43
    parent = "topics"
    [[menu.index]]
    name = "Advanced Scripting Guide"
    url = "/topics/scripting_advanced/"
    weight = 44
    parent = "topics"
    [[menu.index]]
    name = "Dependencies"
    url = "/topics/dependencies/"
    weight = 45
    parent = "topics"
    [[menu.index]]
    name = "GitHub Integration"
    url = "/topics/github/"
    weight = 46
    parent = "topics"
    [[menu.index]]
    name = "Container Registry Integration"
    url = "/topics/dockerhub/"
    weight = 47
    parent = "topics"
    [[menu.index]]
    name = "Generic Gateway"
    url = "/topics/genericgateway/"
    weight = 48
    parent = "topics"
    [[menu.index]]
    name = "Secret Management"
    url = "/topics/secrets/"
    weight = 49
    parent = "topics" 
    [[menu.index]]
    name = "Gateways"
    url = "/topics/gateways/"
    weight = 50
    parent = "topics"
    [[menu.index]]
    name = "Ingress"
    url = "/topics/ingress/"
    weight = 51
    parent = "topics"
    [[menu.index]]
    name = "Projects"
    url = "/topics/projects/"
    weight = 52
    parent = "topics"
    [[menu.index]]
    name = "Securing Brigade"
    url = "/topics/security/"
    weight = 53
    parent = "topics"
    [[menu.index]]
    name = "Storage"
    url = "/topics/storage/"
    weight = 54
    parent = "topics"
    [[menu.index]]
    name = "Workers"
    url = "/topics/workers/"
    weight = 55
    parent = "topics"
    [[menu.index]]
    name = "Testing"
    url = "/topics/testing/"
    weight = 56
    parent = "topics"
    [[menu.index]]
    name = "Developer Guide"
    url = "/topics/developers/"
    weight = 57
    parent = "topics"
    [[menu.index]]
    name = "Releasing Brigade"
    url = "/topics/releasing/"
    weight = 58
    parent = "topics"
[[menu.index]]
    name = "Contributing"
    url = "/contributing/"
    weight = 60


# top navigation - project links
[[menu.main]]
    name = "Docs"
    url = "https://docs.brigade.sh"
    weight = 1

[[menu.main]]
    name = "Examples"
    url = "https://github.com/brigadecore/brigade/tree/master/docs/content/examples"
    weight = 2

[[menu.main]]
    name = "Github"
    url = "https://github.com/brigadecore/brigade"
    weight = 3