baseURL = "https://docs.brigade.sh/"
title = "Brigade Docs"
theme = "techdoc-brigade"
canonifyURLs = "true"
relativeURLs = "true"

[params]
  title = "Brigade"
  description = "Brigade: Event-driven scripting for Kubernetes."

# main docs 'index' menu on left
[[menu.index]]
    name = "Home"
    url = "/"
    weight = 10
[[menu.index]]
    name = "Getting Started"
    url = "/intro/"
    weight = 20
    identifier = "intro"
    [[menu.index]]
    name = "Overview"
    url = "/intro/overview/"
    weight = 21
    parent = "intro"
    [[menu.index]]
    name = "QuickStart"
    url = "/intro/quickstart/"
    weight = 22
    parent = "intro"
    [[menu.index]]
    name = "Installing Brigade"
    url = "/intro/install/"
    weight = 23
    parent = "intro"
    [[menu.index]]
    name = "What to Read Next"
    url = "/intro/readnext/"
    weight = 29
    parent = "intro"

[[menu.index]]
    name = "Topic Guides"
    url = "/topics/"
    weight = 40
    identifier = "topics"
    [[menu.index]]
    name = "Design"
    url = "/topics/design/"
    weight = 41
    parent = "topics"
    [[menu.index]]
    name = "Brigade Roles"
    url = "/topics/roles/"
    weight = 42
    parent = "topics"

    [[menu.index]]
    name = "Operators"
    url = "/topics/operators/"
    weight = 45
    identifier = "operators"
    parent = "topics"
    [[menu.index]]
    name = "Deployment"
    url = "/topics/operators/deploy/"
    weight = 46
    parent = "operators"
    [[menu.index]]
    name = "Securing Brigade"
    url = "/topics/operators/security/"
    weight = 47
    parent = "operators"
    [[menu.index]]
    name = "Gateways"
    url = "/topics/operators/gateways/"
    weight = 48
    parent = "operators"

    [[menu.index]]
    name = "Administrators"
    url = "/topics/administrators/"
    weight = 50
    identifier = "administrators"
    parent = "topics"
    [[menu.index]]
    name = "Authentication"
    url = "/topics/administrators/authentication/"
    weight = 51
    parent = "administrators"
    [[menu.index]]
    name = "Authorization"
    url = "/topics/administrators/authorization/"
    weight = 52
    parent = "administrators"

    [[menu.index]]
    name = "Project Developers"
    url = "/topics/project-developers/"
    weight = 55
    identifier = "project-developers"
    parent = "topics"
    [[menu.index]]
    name = "Projects"
    url = "/topics/project-developers/projects/"
    weight = 56
    parent = "project-developers"
    [[menu.index]]
    name = "Events"
    url = "/topics/project-developers/events/"
    weight = 57
    parent = "project-developers"
    [[menu.index]]
    name = "Secrets"
    url = "/topics/project-developers/secrets/"
    weight = 58
    parent = "project-developers"
    [[menu.index]]
    name = "Using the brig CLI"
    url = "/topics/project-developers/brig/"
    weight = 59
    parent = "project-developers"
    [[menu.index]]
    name = "Brigterm"
    url = "/topics/project-developers/brigterm/"
    weight = 60
    parent = "project-developers"

    [[menu.index]]
    name = "Scripting"
    url = "/topics/scripting/"
    weight = 65
    identifier = "scripting"
    parent = "topics"
    [[menu.index]]
    name = "Scripting Guide"
    url = "/topics/scripting/guide/"
    weight = 66
    parent = "scripting"
    [[menu.index]]
    name = "The Brigadier Library"
    url = "/topics/scripting/brigadier/"
    weight = 67
    parent = "scripting"
    [[menu.index]]
    name = "Advanced Scripting Guide"
    url = "/topics/scripting/advanced/"
    weight = 68
    parent = "scripting"
    [[menu.index]]
    name = "Dependencies"
    url = "/topics/scripting/dependencies/"
    weight = 69
    parent = "scripting"
    [[menu.index]]
    name = "Workers"
    url = "/topics/scripting/workers/"
    weight = 70
    parent = "scripting"

    [[menu.index]]
    name = "Developer Guide"
    url = "/topics/developers/"
    weight = 75
    parent = "topics"

    [[menu.index]]
    name = "Examples"
    url = "/topics/examples/"
    weight = 76
    parent = "topics"

[[menu.index]]
    name = "Releasing Brigade"
    url = "/releasing/"
    weight = 80
    [[menu.index]]
    name = "Contributing"
    url = "/contributing/"
    weight = 81


# top navigation - project links
[[menu.main]]
    name = "Docs"
    url = "https://docs.brigade.sh"
    weight = 1

[[menu.main]]
    name = "Examples"
    url = "https://github.com/brigadecore/brigade/tree/v2/examples"
    weight = 2

[[menu.main]]
    name = "Github"
    url = "https://github.com/brigadecore/brigade"
    weight = 3
