name: Brigade v2 PR

on:
  pull_request:
    branches:
      - v2

jobs:
  build:
    runs-on: windows-latest
    env:
      DOCKER_ORG: brigadecore
    steps:
      - uses: actions/checkout@v2
      - name: Build Windows logger agent
        run: |
          make build-logger-windows
